# Generated by Django 4.2.30 on 2026-05-11 09:51

from django.db import migrations, models


def forwards(apps, schema_editor):
    Order = apps.get_model('pet_core', 'Order')
    Order.objects.filter(status='pending_payment').update(status='confirmed')
    Order.objects.filter(status='in_progress').update(status='confirmed')


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0005_recalc_merchant_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petowner',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='is_admin_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认（待付款）'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.CreateModel(
            name='ChinaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['province'], name='pet_core_ch_provinc_d00b46_idx'), models.Index(fields=['province', 'city'], name='pet_core_ch_provinc_bd0773_idx')],
                'unique_together': {('province', 'city', 'district')},
            },
        ),
    ]
