# Generated by Django 4.2.30 on 2026-05-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0006_merchant_district_petowner_district_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChinaArea',
        ),
    ]
