# Generated by Django 4.2.30 on 2026-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0011_rename_pet_core_va_series__3e09a1_idx_pet_core_va_series__d15150_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vaccine_animal_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
