# Generated by Django 4.2.30 on 2026-05-12 16:15

from django.db import migrations, models


def forwards_dedupe_service_names(apps, schema_editor):
    Service = apps.get_model('pet_core', 'Service')

    qs = Service.objects.all().only('id', 'merchant_id', 'name').order_by('merchant_id', 'name', 'id')
    seen = {}
    updates = []

    for s in qs.iterator(chunk_size=5000):
        key = (s.merchant_id, s.name)
        count = seen.get(key, 0) + 1
        seen[key] = count
        if count == 1:
            continue

        base = s.name or 'Service'
        suffix = f' ({count})'
        max_len = 100
        trimmed = base
        if len(trimmed) + len(suffix) > max_len:
            trimmed = trimmed[: max_len - len(suffix)]
        new_name = trimmed + suffix

        while Service.objects.filter(merchant_id=s.merchant_id, name=new_name).exclude(id=s.id).exists():
            count += 1
            suffix = f' ({count})'
            trimmed = base
            if len(trimmed) + len(suffix) > max_len:
                trimmed = trimmed[: max_len - len(suffix)]
            new_name = trimmed + suffix

        s.name = new_name
        updates.append(s)
        if len(updates) >= 5000:
            Service.objects.bulk_update(updates, ['name'], batch_size=5000)
            updates.clear()

    if updates:
        Service.objects.bulk_update(updates, ['name'], batch_size=5000)


def backwards_dedupe_service_names(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0014_remove_order_vaccine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RunPython(forwards_dedupe_service_names, backwards_dedupe_service_names),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['province', 'city'], name='idx_merchant_province_city'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pet', 'appointment_time'], name='idx_order_pet_time'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'merchant'], name='idx_service_category_merchant'),
        ),
        migrations.AddIndex(
            model_name='vaccinerecord',
            index=models.Index(fields=['pet', 'administered_date'], name='idx_vacrec_pet_admin'),
        ),
        migrations.AddIndex(
            model_name='vaccinerecord',
            index=models.Index(fields=['pet', 'next_due_date'], name='idx_vacrec_pet_due'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('merchant', 'name'), name='uniq_service_name_per_merchant'),
        ),
    ]
