# Generated by Django 4.2.30 on 2026-05-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0016_alter_merchant_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
