# Generated by GPT for schema refactor on 2026-05-13

from django.db import migrations, models
import django.db.models.deletion


def forwards_review_pk_to_id(apps, schema_editor):
    Review = apps.get_model('pet_core', 'Review')
    table = Review._meta.db_table
    qn = schema_editor.quote_name
    vendor = schema_editor.connection.vendor

    if vendor in {'mysql', 'mariadb'}:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"SHOW COLUMNS FROM {qn(table)}")
            cols = {row[0] for row in cursor.fetchall()}

            cursor.execute(f"SHOW INDEX FROM {qn(table)}")
            idx_rows = cursor.fetchall()
            idx_by_name = {}
            for r in idx_rows:
                key_name = r[2]
                col_name = r[4]
                idx_by_name.setdefault(key_name, []).append(col_name)

            pk_cols = idx_by_name.get('PRIMARY') or []
            if pk_cols == ['id']:
                if 'uq_review_order_id' not in idx_by_name:
                    cursor.execute(
                        f"ALTER TABLE {qn(table)} "
                        f"ADD UNIQUE KEY {qn('uq_review_order_id')} ({qn('order_id')})"
                    )
                return

            if 'id' not in cols:
                cursor.execute(
                    f"ALTER TABLE {qn(table)} "
                    f"ADD COLUMN {qn('id')} BIGINT NOT NULL AUTO_INCREMENT, "
                    f"ADD UNIQUE KEY {qn('uq_review_id')} ({qn('id')})"
                )
                cols.add('id')

            has_order_index_non_pk = any(
                name != 'PRIMARY' and ('order_id' in cols_list)
                for name, cols_list in idx_by_name.items()
            )
            if not has_order_index_non_pk:
                cursor.execute(
                    f"ALTER TABLE {qn(table)} "
                    f"ADD INDEX {qn('idx_review_order_id')} ({qn('order_id')})"
                )

            if pk_cols == ['order_id']:
                cursor.execute(f"ALTER TABLE {qn(table)} DROP PRIMARY KEY")

            cursor.execute(f"SHOW INDEX FROM {qn(table)}")
            idx_rows = cursor.fetchall()
            idx_by_name = {}
            for r in idx_rows:
                key_name = r[2]
                col_name = r[4]
                idx_by_name.setdefault(key_name, []).append(col_name)

            pk_cols = idx_by_name.get('PRIMARY') or []
            if pk_cols != ['id']:
                if 'uq_review_id' in idx_by_name:
                    cursor.execute(
                        f"ALTER TABLE {qn(table)} "
                        f"DROP INDEX {qn('uq_review_id')}, "
                        f"ADD PRIMARY KEY ({qn('id')})"
                    )
                else:
                    cursor.execute(f"ALTER TABLE {qn(table)} ADD PRIMARY KEY ({qn('id')})")

            cursor.execute(f"SHOW INDEX FROM {qn(table)}")
            idx_rows = cursor.fetchall()
            idx_by_name = {}
            for r in idx_rows:
                key_name = r[2]
                col_name = r[4]
                idx_by_name.setdefault(key_name, []).append(col_name)

            if 'uq_review_order_id' not in idx_by_name:
                cursor.execute(
                    f"ALTER TABLE {qn(table)} "
                    f"ADD UNIQUE KEY {qn('uq_review_order_id')} ({qn('order_id')})"
                )
        return

    if vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('PRAGMA foreign_keys=OFF;')
            cursor.execute(f'ALTER TABLE {qn(table)} RENAME TO {qn(table + "_old")};')
            cursor.execute(
                f"""
                CREATE TABLE {qn(table)} (
                    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    order_id bigint NOT NULL UNIQUE
                        REFERENCES pet_core_order (id) DEFERRABLE INITIALLY DEFERRED,
                    rating integer NOT NULL,
                    comment text NOT NULL,
                    created_at datetime NOT NULL
                );
                """
            )
            cursor.execute(
                f"""
                INSERT INTO {qn(table)} (order_id, rating, comment, created_at)
                SELECT order_id, rating, comment, created_at FROM {qn(table + "_old")};
                """
            )
            cursor.execute(f'DROP TABLE {qn(table + "_old")};')
            cursor.execute('PRAGMA foreign_keys=ON;')
        return

    raise RuntimeError(f'Unsupported DB vendor for review PK migration: {vendor}')


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0020_remove_pet_is_neutered_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards_review_pk_to_id, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='review',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='review',
                    name='order',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='pet_core.order'),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='duration_months',
        ),
    ]
