# Generated by Django 4.2.30 on 2026-05-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0022_service_idx_service_cat_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='address',
        ),
    ]
