# Generated by Django 4.2.30 on 2026-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0023_remove_merchant_address_remove_petowner_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active', 'approval_status', 'is_admin_disabled', 'merchant', 'id'], name='idx_srv_cat_state_merch_id'),
        ),
    ]
