# Generated by Django 4.2.30 on 2026-05-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='operating_hours',
            field=models.CharField(default='9:00-18:00', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='latest_vaccine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='latest_vaccine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('in_progress', '服务中'), ('pending_payment', '待付款'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FavoriteStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pet_core.merchant')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pet_core.petowner')),
            ],
            options={
                'unique_together': {('owner', 'merchant')},
            },
        ),
    ]
