# Generated by Django 4.2.30 on 2026-05-10 19:29

from django.db import migrations, models


def _split_full_address(full_address: str):
    raw = (full_address or '').strip()
    if not raw:
        return '', '', ''
    parts = raw.split()
    if len(parts) >= 3:
        return parts[0], parts[1], ' '.join(parts[2:])
    return '', '', raw


def forwards(apps, schema_editor):
    PetOwner = apps.get_model('pet_core', 'PetOwner')
    Merchant = apps.get_model('pet_core', 'Merchant')

    owners_to_update = []
    for owner in PetOwner.objects.all().only('user_id', 'province', 'city', 'address_detail', 'address').iterator(chunk_size=2000):
        if owner.province or owner.city or owner.address_detail:
            continue
        p, c, d = _split_full_address(owner.address)
        if p or c or d:
            owner.province = p
            owner.city = c
            owner.address_detail = d
            owners_to_update.append(owner)
        if len(owners_to_update) >= 2000:
            PetOwner.objects.bulk_update(owners_to_update, ['province', 'city', 'address_detail'], batch_size=2000)
            owners_to_update = []
    if owners_to_update:
        PetOwner.objects.bulk_update(owners_to_update, ['province', 'city', 'address_detail'], batch_size=2000)

    merchants_to_update = []
    for merchant in Merchant.objects.all().only('user_id', 'province', 'city', 'address_detail', 'address').iterator(chunk_size=2000):
        if merchant.province or merchant.city or merchant.address_detail:
            continue
        p, c, d = _split_full_address(merchant.address)
        if p or c or d:
            merchant.province = p
            merchant.city = c
            merchant.address_detail = d
            merchants_to_update.append(merchant)
        if len(merchants_to_update) >= 2000:
            Merchant.objects.bulk_update(merchants_to_update, ['province', 'city', 'address_detail'], batch_size=2000)
            merchants_to_update = []
    if merchants_to_update:
        Merchant.objects.bulk_update(merchants_to_update, ['province', 'city', 'address_detail'], batch_size=2000)


def backwards(apps, schema_editor):
    PetOwner = apps.get_model('pet_core', 'PetOwner')
    Merchant = apps.get_model('pet_core', 'Merchant')
    PetOwner.objects.update(province='', city='', address_detail='')
    Merchant.objects.update(province='', city='', address_detail='')


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0003_service_is_active_alter_favoritestore_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petowner',
            name='address_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petowner',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(forwards, backwards),
    ]
