# Generated by Django 4.2.30 on 2026-05-10

from django.db import migrations
from django.db.models import Avg


def forwards(apps, schema_editor):
    Review = apps.get_model('pet_core', 'Review')
    Merchant = apps.get_model('pet_core', 'Merchant')

    avg_by_merchant = {
        row['order__service__merchant']: row['a']
        for row in Review.objects.values('order__service__merchant').annotate(a=Avg('rating'))
    }

    merchants = list(Merchant.objects.all().only('user_id', 'average_rating'))
    for m in merchants:
        m.average_rating = avg_by_merchant.get(m.user_id) or 0
    if merchants:
        Merchant.objects.bulk_update(merchants, ['average_rating'], batch_size=2000)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('pet_core', '0004_merchant_address_detail_merchant_city_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

