# Generated by Django 4.2.30 on 2026-05-11 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0007_delete_chinaarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employee_no', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='amount_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='vaccine_provider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='vaccine_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_vaccine_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('v_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField()),
                ('animal_type', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['animal_type'], name='pet_core_va_animal__224b16_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pet_core.vaccine'),
        ),
    ]
