# Generated by Django 4.2.30 on 2026-05-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0008_administrator_order_amount_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerecord',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='pet_core.vaccine'),
        ),
    ]
