# Generated by Django 4.2.30 on 2026-05-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0012_pet_vaccine_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='pet_core.servicecategory'),
        ),
    ]
