# Generated by Django 4.2.30 on 2026-05-12 15:38

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_vaccine_fields(apps, schema_editor):
    Order = apps.get_model('pet_core', 'Order')
    VaccineOrderDetail = apps.get_model('pet_core', 'VaccineOrderDetail')

    qs = Order.objects.filter(vaccine_id__isnull=False).only('id', 'vaccine_id', 'vaccine_provider_name', 'vaccine_remarks')
    buf = []
    for o in qs.iterator(chunk_size=2000):
        buf.append(
            VaccineOrderDetail(
                order_id=o.id,
                vaccine_id=o.vaccine_id,
                provider_name=o.vaccine_provider_name or '',
                remarks=o.vaccine_remarks or '',
            )
        )
        if len(buf) >= 5000:
            VaccineOrderDetail.objects.bulk_create(buf, ignore_conflicts=True, batch_size=5000)
            buf.clear()
    if buf:
        VaccineOrderDetail.objects.bulk_create(buf, ignore_conflicts=True, batch_size=5000)


def backwards_copy_vaccine_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0013_merchant_primary_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineOrderDetail',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vaccine_detail', serialize=False, to='pet_core.order')),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='pet_core.vaccine')),
            ],
        ),
        migrations.RunPython(forwards_copy_vaccine_fields, backwards_copy_vaccine_fields),
        migrations.RemoveField(
            model_name='order',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vaccine_provider_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vaccine_remarks',
        ),
    ]
