# Generated by Django 4.2.30 on 2026-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0015_alter_servicecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='license_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['is_verified', 'primary_category'], name='idx_merchant_verified_cat'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['merchant', 'is_active', 'approval_status', 'is_admin_disabled'], name='idx_service_merch_state'),
        ),
    ]
