# Generated by Django 4.2.30 on 2026-05-13 03:33

from django.db import migrations, models


def _drop_column_if_exists(apps, schema_editor, table_name: str, column_name: str, model_name: str, field_name: str):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    model = apps.get_model('pet_core', model_name)
    try:
        field = model._meta.get_field(field_name)
    except Exception:
        return

    with schema_editor.connection.cursor() as cursor:
        cols = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    col_names = {c.name for c in cols}
    if column_name not in col_names:
        return
    qn = schema_editor.quote_name
    schema_editor.execute(f'ALTER TABLE {qn(table_name)} DROP COLUMN {qn(column_name)};')


def forwards_drop_columns(apps, schema_editor):
    _drop_column_if_exists(apps, schema_editor, 'pet_core_order', 'external_id', 'Order', 'external_id')
    _drop_column_if_exists(apps, schema_editor, 'pet_core_petowner', 'preferences', 'PetOwner', 'preferences')
    _drop_column_if_exists(apps, schema_editor, 'pet_core_servicecategory', 'description', 'ServiceCategory', 'description')


def _rename_m2m_table(schema_editor, old_name: str, new_name: str):
    existing = set(schema_editor.connection.introspection.table_names())
    if old_name in existing and new_name not in existing:
        qn = schema_editor.quote_name
        schema_editor.execute(f'RENAME TABLE {qn(old_name)} TO {qn(new_name)};')


def forwards_rename_user_m2m_tables(apps, schema_editor):
    _rename_m2m_table(schema_editor, 'pet_core_user_groups', 'django_user_groups')
    _rename_m2m_table(schema_editor, 'pet_core_user_user_permissions', 'django_user_user_permissions')


def backwards_rename_user_m2m_tables(apps, schema_editor):
    _rename_m2m_table(schema_editor, 'django_user_groups', 'pet_core_user_groups')
    _rename_m2m_table(schema_editor, 'django_user_user_permissions', 'pet_core_user_user_permissions')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pet_core', '0017_remove_service_duration_minutes_order_external_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards_drop_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='order',
                    name='external_id',
                ),
                migrations.RemoveField(
                    model_name='petowner',
                    name='preferences',
                ),
                migrations.RemoveField(
                    model_name='servicecategory',
                    name='description',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    forwards_rename_user_m2m_tables,
                    reverse_code=backwards_rename_user_m2m_tables,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='groups',
                    field=models.ManyToManyField(
                        blank=True,
                        db_table='django_user_groups',
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='user_permissions',
                    field=models.ManyToManyField(
                        blank=True,
                        db_table='django_user_user_permissions',
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
        ),
    ]
