# Generated by Django 4.2.30 on 2026-05-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0018_remove_order_external_id_remove_petowner_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='latest_vaccine_date',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='latest_vaccine_name',
        ),
    ]
