# Generated by Django 4.2.30 on 2026-05-13 08:21

from django.db import migrations, models


def forwards_clear_remarks(apps, schema_editor):
    qn = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"UPDATE {qn('pet_core_vaccinerecord')} "
            f"SET {qn('remarks')}='' "
            f"WHERE {qn('remarks')} IS NOT NULL AND {qn('remarks')}<>''"
        )
        cursor.execute(
            f"UPDATE {qn('pet_core_vaccineorderdetail')} "
            f"SET {qn('remarks')}='' "
            f"WHERE {qn('remarks')} IS NOT NULL AND {qn('remarks')}<>''"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0019_remove_pet_latest_vaccine_date_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_clear_remarks, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pet',
            name='is_neutered',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccine_animal_type',
        ),
        migrations.RemoveField(
            model_name='vaccineorderdetail',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='provider_name',
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Bird', 'Bird'), ('Cat', 'Cat'), ('Dog', 'Dog'), ('Ferret', 'Ferret'), ('Hamster', 'Hamster'), ('Hedgehog', 'Hedgehog'), ('Rabbit', 'Rabbit'), ('Snake', 'Snake'), ('Turtle', 'Turtle')], max_length=50),
        ),
    ]
