# Generated by Django 4.2.30 on 2026-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0021_review_add_id_remove_vaccine_duration_months'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active', 'approval_status', 'is_admin_disabled', 'id'], name='idx_service_cat_state_id'),
        ),
    ]
